# SOURCE
source 'https://github.com/blodely/LYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

use_frameworks!

target 'PreferencesKit_Example' do
  pod 'PreferencesKit', :path => '../'

  target 'PreferencesKit_Tests' do
    inherit! :search_paths

    
  end
end
