# SOURCE
source 'https://github.com/blodely/LYSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

target 'PreferencesKit_Example' do
  pod 'PreferencesKit', :path => '../'

end
