# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PreferencesSample' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PreferencesSample

  # File Manager
  pod 'FCFileManager', '~> 1.0.18'

  target 'PreferencesSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PreferencesSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
